name: Scrape vLLM Wheels

on:
  workflow_dispatch:
    inputs:
      max_commits:
        description: 'Maximum number of commits to check'
        required: false
        default: '50'
        type: string
      max_releases:
        description: 'Maximum number of GitHub releases to check'
        required: false
        default: '20'
        type: string
      max_versions:
        description: 'Maximum number of PyPI versions to check'
        required: false
        default: '20'
        type: string
      wheels_only:
        description: 'Only include wheel files (no source distributions)'
        required: false
        default: true
        type: boolean
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'

jobs:
  scrape-wheels:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Run wheel scraper
      run: |
        python3 scrape_vllm_wheels.py \
          --all-sources \
          --max-commits ${{ github.event.inputs.max_commits || '50' }} \
          --max-releases ${{ github.event.inputs.max_releases || '20' }} \
          --max-versions ${{ github.event.inputs.max_versions || '20' }} \
          ${{ github.event.inputs.wheels_only == 'true' && '--wheels-only' || '' }} \
          --output data/wheels.json \
          --verbose
    
    - name: Generate CSV file
      run: python3 generate_csv.py
    
    - name: Generate summary stats
      run: python3 generate_stats.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update wheel data - $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          git push
        fi 